# This is the workflow name
name: Hello

# Runs on a trigger
on: workflow_dispatch

# These are jobs inside the workflow
jobs:
  # This is the name of the first job
  greet:
    # This is the GitHub runner
    runs-on: ubuntu-latest
    steps:
      - name: Say hello to users
        run: echo "Hello dosto"

      - name: Say hello to username
        run: echo "Hello $USER"

  # This is the name of the second job
  details:
    runs-on: ubuntu-latest
    steps:
      - name: Check version of python, docker, etc.
        run: |
          docker --version
          python3 --version
